In [8]:
import pandas as pd

In [25]:
df=pd.read_excel("Raw Data.xlsx")
df.head()

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Country,Coffee Type,Roast Type,Size,Unit Price,Sales
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       1000 non-null   object
 1   Order Date     1000 non-null   datetime64[ns]
 2   Customer ID    1000 non-null   object
 3   Product ID     1000 non-null   object
 4   Quantity       1000 non-null   int64
 5   Customer Name  0 non-null      float64
 6   Email          0 non-null      float64
 7   Country        0 non-null      float64
 8   Coffee Type    0 non-null      float64
 9   Roast Type     0 non-null      float64
 10  Size           0 non-null      float64
 11  Unit Price     0 non-null      float64
 12  Sales          0 non-null      float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(3)
memory usage: 101.7+ KB

In [27]:
df.isnull().sum()

Order ID            0
Order Date          0
Customer ID         0
Product ID          0
Quantity            0
Customer Name    1000
Email            1000
Country          1000
Coffee Type      1000
Roast Type       1000
Size             1000
Unit Price       1000
Sales            1000
dtype: int64

In [28]:
df.dropna(inplace=True)
df.isnull().sum()

Order ID         0
Order Date       0
Customer ID      0
Product ID       0
Quantity         0
Customer Name    0
Email            0
Country          0
Coffee Type      0
Roast Type       0
Size             0
Unit Price       0
Sales            0
dtype: int64

In [29]:
df["Order Date"]=pd.to_datetime(df["Order Date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       0 non-null      object
 1   Order Date     0 non-null      datetime64[ns]
 2   Customer ID    0 non-null      object
 3   Product ID     0 non-null      object
 4   Quantity       0 non-null      int64
 5   Customer Name  0 non-null      float64
 6   Email          0 non-null      float64
 7   Country        0 non-null      float64
 8   Coffee Type    0 non-null      float64
 9   Roast Type     0 non-null      float64
 10  Size           0 non-null      float64
 11  Unit Price     0 non-null      float64
 12  Sales          0 non-null      float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(3)
memory usage: 0.0+ bytes

In [31]:
import pandas as pd

# Load each sheet separately
orders = pd.read_excel("Raw Data.xlsx", sheet_name="orders")
customers = pd.read_excel("Raw Data.xlsx", sheet_name="customers")
products = pd.read_excel("Raw Data.xlsx", sheet_name="products")

print(orders.columns)
print(customers.columns)
print(products.columns)

Index(['Order ID', 'Order Date', 'Customer ID', 'Product ID', 'Quantity',
       'Customer Name', 'Email', 'Country', 'Coffee Type', 'Roast Type',
       'Size', 'Unit Price', 'Sales'],
      dtype='object')
Index(['Customer ID', 'Customer Name', 'Email', 'Phone Number',
       'Address Line 1', 'City', 'Country', 'Postcode', 'Loyalty Card'],
      dtype='object')
Index(['Product ID', 'Coffee Type', 'Roast Type', 'Size', 'Unit Price',
       'Price per 100g', 'Profit'],
      dtype='object')

In [32]:
# Merge orders with customers using Customer ID
df = orders.merge(customers[['Customer ID', 'Customer Name', 'Email', 'Country', 'Loyalty Card']], 
                  on='Customer ID', 
                  how='left')

# Merge result with products using Product ID
df = df.merge(products[['Product ID', 'Coffee Type', 'Roast Type', 'Size', 'Unit Price', 'Profit']], 
              on='Product ID', 
              how='left')

df.head()

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name_x,Email_x,Country_x,Coffee Type_x,Roast Type_x,...,Sales,Customer Name_y,Email_y,Country_y,Loyalty Card,Coffee Type_y,Roast Type_y,Size_y,Unit Price_y,Profit
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,NaN,NaN,NaN,NaN,NaN,...,NaN,Aloisia Allner,aallner0@lulu.com,United States,Yes,Rob,M,1.0,9.950,0.5970
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,NaN,NaN,NaN,NaN,NaN,...,NaN,Aloisia Allner,aallner0@lulu.com,United States,Yes,Exc,M,0.5,8.250,0.9075
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,NaN,NaN,NaN,NaN,NaN,...,NaN,Jami Redholes,jredholes2@tmall.com,United States,Yes,Ara,L,1.0,12.950,1.1655
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,NaN,NaN,NaN,NaN,NaN,...,NaN,Christoffer O' Shea,NaN,Ireland,No,Exc,M,1.0,13.750,1.5125
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,NaN,NaN,NaN,NaN,NaN,...,NaN,Christoffer O' Shea,NaN,Ireland,No,Rob,L,2.5,27.485,1.6491

In [33]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order ID         1000 non-null   object
 1   Order Date       1000 non-null   datetime64[ns]
 2   Customer ID      1000 non-null   object
 3   Product ID       1000 non-null   object
 4   Quantity         1000 non-null   int64
 5   Customer Name_x  0 non-null      float64
 6   Email_x          0 non-null      float64
 7   Country_x        0 non-null      float64
 8   Coffee Type_x    0 non-null      float64
 9   Roast Type_x     0 non-null      float64
 10  Size_x           0 non-null      float64
 11  Unit Price_x     0 non-null      float64
 12  Sales            0 non-null      float64
 13  Customer Name_y  1000 non-null   object
 14  Email_y          794 non-null    object
 15  Country_y        1000 non-null   object
 16  Loyalty Card     1000 non-null   object
 17  Coffee Type_y    1000 non-null   object
 18  Roast Type_y     1000 non-null   object
 19  Size_y           1000 non-null   float64
 20  Unit Price_y     1000 non-null   float64
 21  Profit           1000 non-null   float64
dtypes: datetime64[ns](1), float64(11), int64(1), object(9)
memory usage: 172.0+ KB

Order ID              0
Order Date            0
Customer ID           0
Product ID            0
Quantity              0
Customer Name_x    1000
Email_x            1000
Country_x          1000
Coffee Type_x      1000
Roast Type_x       1000
Size_x             1000
Unit Price_x       1000
Sales              1000
Customer Name_y       0
Email_y             206
Country_y             0
Loyalty Card          0
Coffee Type_y         0
Roast Type_y          0
Size_y                0
Unit Price_y          0
Profit                0
dtype: int64

In [34]:
# Drop the empty _x columns and rename _y columns
df = df.drop(columns=['Customer Name_x', 'Email_x', 'Country_x', 
                       'Coffee Type_x', 'Roast Type_x', 'Size_x', 
                       'Unit Price_x', 'Sales'])

df = df.rename(columns={
    'Customer Name_y': 'Customer Name',
    'Email_y': 'Email',
    'Country_y': 'Country',
    'Coffee Type_y': 'Coffee Type',
    'Roast Type_y': 'Roast Type',
    'Size_y': 'Size',
    'Unit Price_y': 'Unit Price'
})

# Calculate Sales column
df['Sales'] = df['Quantity'] * df['Unit Price']

print(df.columns)
print(df.isnull().sum())

Index(['Order ID', 'Order Date', 'Customer ID', 'Product ID', 'Quantity',
       'Customer Name', 'Email', 'Country', 'Loyalty Card', 'Coffee Type',
       'Roast Type', 'Size', 'Unit Price', 'Profit', 'Sales'],
      dtype='object')
Order ID           0
Order Date         0
Customer ID        0
Product ID         0
Quantity           0
Customer Name      0
Email            206
Country            0
Loyalty Card       0
Coffee Type        0
Roast Type         0
Size               0
Unit Price         0
Profit             0
Sales              0
dtype: int64

In [35]:
# 1. Which coffee type sells most?
df.groupby('Coffee Type')['Sales'].sum().sort_values(ascending=False)

Coffee Type
Exc    12306.440
Lib    12054.075
Ara    11768.495
Rob     9005.245
Name: Sales, dtype: float64

In [36]:
# 2. Which country generates most revenue?
df.groupby('Country')['Sales'].sum().sort_values(ascending=False)

Country
United States     35638.885
Ireland            6696.865
United Kingdom     2798.505
Name: Sales, dtype: float64

In [37]:
# 3. Monthly sales trend
df['Month'] = df['Order Date'].dt.to_period('M')
df.groupby('Month')['Sales'].sum()

Month
2019-01     828.985
2019-02     987.405
2019-03    1021.140
2019-04    1680.750
2019-05     398.565
2019-06    1384.680
2019-07    1004.135
2019-08     706.345
2019-09    1277.020
2019-10     884.970
2019-11     823.385
2019-12    1189.785
2020-01     566.950
2020-02    1798.340
2020-03     914.790
2020-04     761.810
2020-05     939.355
2020-06    1438.440
2020-07    1308.945
2020-08     300.400
2020-09     713.050
2020-10    1514.705
2020-11    1108.865
2020-12     751.895
2021-01     837.685
2021-02     958.830
2021-03    1544.640
2021-04    1005.585
2021-05     907.690
2021-06     864.530
2021-07     763.105
2021-08    1075.910
2021-09    1643.575
2021-10    1400.400
2021-11    1616.180
2021-12    1147.980
2022-01    1269.415
2022-02     393.630
2022-03    1315.205
2022-04     776.450
2022-05    1002.370
2022-06    1155.390
2022-07     906.730
2022-08     244.245
Freq: M, Name: Sales, dtype: float64